==19285== Memcheck, a memory error detector
==19285== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==19285== Using Valgrind-3.10.0.SVN and LibVEX; rerun with -h for copyright info
==19285== Command: python test_arithmetic.py
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B7B5: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x5dfd020 is 1,056 bytes inside a block of size 2,731 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==  Address 0x5e5b020 is 2,448 bytes inside a block of size 2,494 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x5e45020 is 224 bytes inside a block of size 368 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4E5C58: PyList_Append (in /usr/bin/python2.7)
==19285==    by 0x4A3DD3: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A409B: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CD5: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x5df0020 is 10,224 bytes inside a block of size 11,567 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==  Address 0x5df3020 is 1,024 bytes inside a block of size 1,384 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x54B86D: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==  Address 0x5f60020 is 3,696 bytes inside a block of size 4,784 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CF8: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Conditional jump or move depends on uninitialised value(s)
==19285==    at 0x540017: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==19285==    by 0x52B852: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Use of uninitialised value of size 8
==19285==    at 0x54002F: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==19285==    by 0x52B852: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==19285==    by 0x52B852: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x5fad020 is 528 bytes inside a block of size 676 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x538954: PyGrammar_AddAccelerators (in /usr/bin/python2.7)
==19285==    by 0x52B852: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E0B0: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x6033020 is 0 bytes after a block of size 768 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x515136: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AFC90: ??? (in /usr/bin/python2.7)
==19285==    by 0x477E66: ??? (in /usr/bin/python2.7)
==19285==    by 0x477F7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285== 
==19285== Conditional jump or move depends on uninitialised value(s)
==19285==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==19285==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x594759: PyParser_ASTFromFile (in /usr/bin/python2.7)
==19285==    by 0x4699A6: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285== 
==19285== Use of uninitialised value of size 8
==19285==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==19285==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x594759: PyParser_ASTFromFile (in /usr/bin/python2.7)
==19285==    by 0x4699A6: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x5741E4: ??? (in /usr/bin/python2.7)
==19285==    by 0x5743DA: ??? (in /usr/bin/python2.7)
==19285==    by 0x5743DA: ??? (in /usr/bin/python2.7)
==19285==    by 0x5AECFD: PyNode_Free (in /usr/bin/python2.7)
==19285==    by 0x59478E: PyParser_ASTFromFile (in /usr/bin/python2.7)
==19285==    by 0x4699A6: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285==  Address 0x60c3020 is 34,528 bytes inside a block of size 36,032 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x52B594: ??? (in /usr/bin/python2.7)
==19285==    by 0x594759: PyParser_ASTFromFile (in /usr/bin/python2.7)
==19285==    by 0x4699A6: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AECAE: ??? (in /usr/bin/python2.7)
==19285==    by 0x4798D0: ??? (in /usr/bin/python2.7)
==19285==    by 0x478A1B: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285==  Address 0x60c8020 is 400 bytes inside a block of size 768 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A991B: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AA177: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AA177: ??? (in /usr/bin/python2.7)
==19285==    by 0x4C88F0: PySymtable_Build (in /usr/bin/python2.7)
==19285==    by 0x47E032: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x52738D: ??? (in /usr/bin/python2.7)
==19285==    by 0x47B3EF: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285==  Address 0x60c8020 is 400 bytes inside a block of size 768 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A991B: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AA177: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AA177: ??? (in /usr/bin/python2.7)
==19285==    by 0x4C88F0: PySymtable_Build (in /usr/bin/python2.7)
==19285==    by 0x47E032: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E0B0: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285==    by 0x5076EC4: (below main) (libc-start.c:287)
==19285==  Address 0x60cb020 is 0 bytes after a block of size 352 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4EC49C: PyCode_Optimize (in /usr/bin/python2.7)
==19285==    by 0x4A0126: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x46964C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4699E2: PyRun_FileExFlags (in /usr/bin/python2.7)
==19285==    by 0x469F1B: PyRun_SimpleFileExFlags (in /usr/bin/python2.7)
==19285==    by 0x46AB80: Py_Main (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x472687: ??? (in /usr/bin/python2.7)
==19285==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==19285==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x4CD49D: ??? (in /usr/bin/python2.7)
==19285==  Address 0x6428020 is 1,488 bytes inside a block of size 1,559 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==19285==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==19285==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==19285==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x574286: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BC2B: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==  Address 0x6435020 is 35,408 bytes inside a block of size 36,032 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x52B594: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x643c020 is 16 bytes inside a block of size 32 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A0323: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x4B0452: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A1A9: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x643a020 is 384 bytes inside a block of size 768 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x5392BC: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A991B: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AA177: ??? (in /usr/bin/python2.7)
==19285==    by 0x4C88F0: PySymtable_Build (in /usr/bin/python2.7)
==19285==    by 0x47E032: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x515136: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2FB: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x643c020 is 16 bytes inside a block of size 32 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A0323: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x5A5092: ??? (in /usr/bin/python2.7)
==19285==    by 0x57929C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x643d020 is 688 bytes inside a block of size 1,536 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x515136: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2FB: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x53A541: ??? (in /usr/bin/python2.7)
==19285==    by 0x55C5B8: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x4CD49D: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DBEB: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==  Address 0x6428020 is 1,488 bytes inside a block of size 1,559 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==19285==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==19285==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==19285==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x50C437: _PyString_Resize (in /usr/bin/python2.7)
==19285==    by 0x472AA4: ??? (in /usr/bin/python2.7)
==19285==    by 0x4733C9: ??? (in /usr/bin/python2.7)
==19285==    by 0x530824: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==  Address 0x6496020 is 16 bytes after a block of size 48 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x46E3B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52CCBB: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Conditional jump or move depends on uninitialised value(s)
==19285==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==19285==    by 0x5377E7: PyNode_AddChild (in /usr/bin/python2.7)
==19285==    by 0x537E6E: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285== 
==19285== Use of uninitialised value of size 8
==19285==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==19285==    by 0x5377E7: PyNode_AddChild (in /usr/bin/python2.7)
==19285==    by 0x537E6E: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x5f3e020 is 0 bytes after a block of size 656 alloc'd
==19285==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x517A39: _PyObject_GC_NewVar (in /usr/bin/python2.7)
==19285==    by 0x4F3142: PyFrame_New (in /usr/bin/python2.7)
==19285==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DD5A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x6461020 is 272 bytes inside a block of size 464 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4E5C58: PyList_Append (in /usr/bin/python2.7)
==19285==    by 0x4A3DD3: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A409B: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3F32: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CD5: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B7B5: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x54B791: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DD5A: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x6466020 is 2,016 bytes inside a block of size 2,152 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4E5C58: PyList_Append (in /usr/bin/python2.7)
==19285==    by 0x4A3DD3: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4104: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3FA7: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A4085: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CD5: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x46B0E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x60d8020 is 32 bytes inside a block of size 200 free'd
==19285==    at 0x4C2CE8E: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4E5C58: PyList_Append (in /usr/bin/python2.7)
==19285==    by 0x4A3DD3: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A3F09: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A409B: ??? (in /usr/bin/python2.7)
==19285==    by 0x585CD5: PyMarshal_ReadObjectFromString (in /usr/bin/python2.7)
==19285==    by 0x585D7F: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x46B0E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D77B: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==19285==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==19285==    by 0x52CE52: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x650d020 is 0 bytes inside a block of size 32 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x56EBAB: ??? (in /usr/bin/python2.7)
==19285==    by 0x53A572: ??? (in /usr/bin/python2.7)
==19285==    by 0x55C5B8: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Conditional jump or move depends on uninitialised value(s)
==19285==    at 0x5BB279: ??? (in /usr/bin/python2.7)
==19285==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Use of uninitialised value of size 8
==19285==    at 0x5BB28E: ??? (in /usr/bin/python2.7)
==19285==    by 0x537DEC: PyParser_AddToken (in /usr/bin/python2.7)
==19285==    by 0x52B4B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52BE22: PyParser_ASTFromString (in /usr/bin/python2.7)
==19285==    by 0x52BFFB: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AF42F: ??? (in /usr/bin/python2.7)
==19285==    by 0x4B0299: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A1A9: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x82b7020 is 8 bytes after a block of size 152 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x477035: ??? (in /usr/bin/python2.7)
==19285==    by 0x47761B: ??? (in /usr/bin/python2.7)
==19285==    by 0x5791A7: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x47840F: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x82b9020 is 752 bytes inside a block of size 768 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x573D7A: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A16D: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x54B87B: ??? (in /usr/bin/python2.7)
==19285==    by 0x52C073: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==    by 0x5B7449: PyImport_ExecCodeModuleEx (in /usr/bin/python2.7)
==19285==    by 0x579F0E: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==19285==  Address 0x67ec020 is 0 bytes inside a block of size 64 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==19285==    by 0x497381: ??? (in /usr/bin/python2.7)
==19285==    by 0x539AAB: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x538F26: ??? (in /usr/bin/python2.7)
==19285==    by 0x539AAB: ??? (in /usr/bin/python2.7)
==19285==    by 0x5392FE: ??? (in /usr/bin/python2.7)
==19285==    by 0x497381: ??? (in /usr/bin/python2.7)
==19285==    by 0x538FE2: ??? (in /usr/bin/python2.7)
==19285==    by 0x538F26: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x515136: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AFC43: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==  Address 0x833d020 is 0 bytes inside a block of size 32 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x539994: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A0323: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AF42F: ??? (in /usr/bin/python2.7)
==19285==    by 0x47986C: ??? (in /usr/bin/python2.7)
==19285==    by 0x477FFE: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C2C0: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x833f020 is 208 bytes inside a block of size 320 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x4EC48C: PyCode_Optimize (in /usr/bin/python2.7)
==19285==    by 0x4A0126: ??? (in /usr/bin/python2.7)
==19285==    by 0x47A15C: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C3A3: ??? (in /usr/bin/python2.7)
==19285==    by 0x579252: ??? (in /usr/bin/python2.7)
==19285==    by 0x47C403: ??? (in /usr/bin/python2.7)
==19285==    by 0x47E351: PyAST_Compile (in /usr/bin/python2.7)
==19285==    by 0x52C017: PyRun_StringFlags (in /usr/bin/python2.7)
==19285==    by 0x53173E: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x54000E: PyObject_Free (in /usr/bin/python2.7)
==19285==    by 0x54B76E: ??? (in /usr/bin/python2.7)
==19285==    by 0x579F2C: ??? (in /usr/bin/python2.7)
==19285==    by 0x46B0E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x5B7391: PyEval_EvalCode (in /usr/bin/python2.7)
==19285==  Address 0x83b5020 is 54,752 bytes inside a block of size 57,245 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x585D8A: PyMarshal_ReadLastObjectFromFile (in /usr/bin/python2.7)
==19285==    by 0x585DBD: ??? (in /usr/bin/python2.7)
==19285==    by 0x579EC4: ??? (in /usr/bin/python2.7)
==19285==    by 0x46B0E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D3A2: ??? (in /usr/bin/python2.7)
==19285==    by 0x55D82F: ??? (in /usr/bin/python2.7)
==19285==    by 0x55DB36: PyImport_ImportModuleLevel (in /usr/bin/python2.7)
==19285==    by 0x4755E6: ??? (in /usr/bin/python2.7)
==19285==    by 0x4DA20A: PyEval_CallObjectWithKeywords (in /usr/bin/python2.7)
==19285==    by 0x52E6D6: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x56E90A: PyObject_GC_Del (in /usr/bin/python2.7)
==19285==    by 0x538FC6: ??? (in /usr/bin/python2.7)
==19285==    by 0x5390E0: ??? (in /usr/bin/python2.7)
==19285==    by 0x52C94D: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==19285==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==19285==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==19285==  Address 0x85f1020 is 0 bytes after a block of size 768 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x527BFF: ??? (in /usr/bin/python2.7)
==19285==    by 0x4AD36B: _PyObject_GenericSetAttrWithDict (in /usr/bin/python2.7)
==19285==    by 0x4CED55: ??? (in /usr/bin/python2.7)
==19285==    by 0x4CF1B6: ??? (in /usr/bin/python2.7)
==19285==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D8378: ??? (in /usr/bin/python2.7)
==19285==    by 0x4F5D0A: ??? (in /usr/bin/python2.7)
==19285== 
==19285== Invalid read of size 4
==19285==    at 0x5BB270: ??? (in /usr/bin/python2.7)
==19285==    by 0x5AC787: _PyObject_GC_Resize (in /usr/bin/python2.7)
==19285==    by 0x4F31AF: PyFrame_New (in /usr/bin/python2.7)
==19285==    by 0x56CE48: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==19285==    by 0x54A327: PyObject_CallFunctionObjArgs (in /usr/bin/python2.7)
==19285==    by 0x598B5A: ??? (in /usr/bin/python2.7)
==19285==    by 0x4CE73C: ??? (in /usr/bin/python2.7)
==19285==    by 0x4A1F81: ??? (in /usr/bin/python2.7)
==19285==    by 0x52C6D4: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x56D0A9: ??? (in /usr/bin/python2.7)
==19285==    by 0x4D9853: ??? (in /usr/bin/python2.7)
==19285==  Address 0x111c9020 is 0 bytes after a block of size 16 free'd
==19285==    at 0x4C2BDEC: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19285==    by 0x6F3FCCA: g_slice_free_chain_with_offset (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4000.0)
==19285==    by 0x6C9E22B: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4000.0)
==19285==    by 0x6C9DFD2: ??? (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4000.0)
==19285==    by 0x6CA1BA4: g_object_set_valist (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4000.0)
==19285==    by 0x6CA2396: g_object_set (in /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4000.0)
==19285==    by 0x892D4DD: vips_object_free_argument (object.c:937)
==19285==    by 0x892CBBE: vips_argument_map (object.c:568)
==19285==    by 0x892D50D: vips_argument_free_all (object.c:957)
==19285==    by 0x892D572: vips_object_dispose (object.c:989)
==19285==    by 0x8944330: vips_operation_dispose (operation.c:220)
==19285==    by 0x8950870: vips_system_dispose (system.c:108)
==19285== 
==19285== Invalid read of size 8
==19285==    at 0x683B580: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x683A8CC: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x683688B: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x682C82D: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==19285== 
==19285== 
==19285== Process terminating with default action of signal 11 (SIGSEGV)
==19285==  Access not within mapped region at address 0x0
==19285==    at 0x683B580: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x683A8CC: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x683688B: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x682C82D: ??? (in /usr/lib/python2.7/dist-packages/gi/_gi.so)
==19285==    by 0x52CC1F: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x52CF31: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==    by 0x55C593: PyEval_EvalCodeEx (in /usr/bin/python2.7)
==19285==    by 0x52CA8C: PyEval_EvalFrameEx (in /usr/bin/python2.7)
==19285==  If you believe this happened as a result of a stack
==19285==  overflow in your program's main thread (unlikely but
==19285==  possible), you can try to increase the size of the
==19285==  main thread stack using the --main-stacksize= flag.
==19285==  The main thread stack size used in this run was 8388608.
==19285== 
==19285== HEAP SUMMARY:
==19285==     in use at exit: 9,373,405 bytes in 24,848 blocks
==19285==   total heap usage: 105,481 allocs, 80,633 frees, 21,521,301 bytes allocated
==19285== 
==19285== LEAK SUMMARY:
==19285==    definitely lost: 0 bytes in 0 blocks
==19285==    indirectly lost: 0 bytes in 0 blocks
==19285==      possibly lost: 32,894 bytes in 58 blocks
==19285==    still reachable: 3,243,770 bytes in 7,814 blocks
==19285==         suppressed: 5,843,669 bytes in 15,154 blocks
==19285== Rerun with --leak-check=full to see details of leaked memory
==19285== 
==19285== For counts of detected and suppressed errors, rerun with: -v
==19285== Use --track-origins=yes to see where uninitialised values come from
==19285== ERROR SUMMARY: 495 errors from 42 contexts (suppressed: 0 from 0)
